language: python

sudo: false

env:
  global:
    - TOOLS='ldoc luacov'
    - DEPENDS='ansicolors specl'
  matrix:
    - VLUA=lua=5.4    EXTRA_ROCKS=std.strict
    - VLUA=lua=5.3    EXTRA_ROCKS=std.strict
    - VLUA=lua=5.2    EXTRA_ROCKS=std.strict
    - VLUA=lua=5.1    EXTRA_ROCKS=std.strict
    - VLUA=luajit=2.1 EXTRA_ROCKS=std.strict
    - VLUA=luajit=2.0 EXTRA_ROCKS=std.strict
    - VLUA=lua=5.4
    - VLUA=lua=5.3
    - VLUA=lua=5.2
    - VLUA=lua=5.1
    - VLUA=luajit=2.1
    - VLUA=luajit=2.0

before_install:
  - pip install hererocks
  - hererocks here --luarocks 3 --$VLUA --patch
  - export PATH="$PWD/here/bin:$PATH"

  # Some tools are not yet ported to Lua 5.4
  - if test "$VLUA" == 'lua=5.4'; then
      hererocks tools --lua=5.1;
      PATH="$PATH:$PWD/tools/bin";
    fi

install:
  # Install rocks we depend on
  - for rock in $DEPENDS${EXTRA_ROCKS+ $EXTRA_ROCKS}; do
      luarocks install $rock;
    done
  - if test "$VLUA" == 'lua=5.4'; then
      LUAROCKS_TOOLARGS=" --lua-dir=$PWD/tools --tree=$PWD/tools";
    fi;
    for rock in $TOOLS; do
      luarocks$LUAROCKS_TOOLARGS install $rock;
    done

script:
  - make all doc
  - luarocks make
  - make check SPECL_OPTS='-vfreport --coverage'

after_success:
  - bash <(curl -s https://codecov.io/bash) -f luacov.report.out

notifications:
  slack: aspirinc:JyWeNrIdS0J5nf2Pn2BS1cih
