name: spec

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        lua-version: ["5.4", "5.3", "5.2", "5.1", "luajit"]
        strict: ["std.strict", ""]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.lua-version }}

      - uses: leafo/gh-actions-luarocks@v4
        with:
          luaRocksVersion: 3.9.2

      - name: install
        run: |
          sudo apt-get install -y libyaml-dev
          test -n "${{ matrix.strict }}" && luarocks install std.strict || true

      - name: build
        run: |
          luarocks install ldoc
          make all doc
          luarocks make

      - name: test
        run: |
          luarocks test --prepare
          make check SPECL_OPTS='-vfreport --coverage'
          bash <(curl -s https://codecov.io/bash) -f luacov.report.out
